services:

  elasticsearch:
    image: elasticsearch:9.2.0
    container_name: ${ES}
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=${ES_SECURITY}
      - ELASTIC_PASSWORD=${ES_PASSWORD}
    ports:
      # dev
      ${ES_PORT}:9200
      # prod
      #- 127.0.0.1:${ES_PORT}:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2g

volumes:
  elasticsearch_data: