services:

  elasticsearch:
    image: elasticsearch:8.19.5
    container_name: ${ES}
    environment:
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - discovery.type=single-node
      - xpack.security.enabled=${ES_SECURITY}
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin='*'
    ports:
      # dev
      - ${ES_PORT}:9200
      # prod
      #- 127.0.0.1:${ES_PORT}:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g

volumes:
  elasticsearch_data: