# https://rabbitmq.com/configure.html#env-variable-interpolation

# https://hub.docker.com/_/rabbitmq

services:

    rabbit-mq:
        container_name: ${RABBIT}
        image: rabbitmq:3-management-alpine
        restart: always
        ports:
            - ${RABBIT_PORT}:5672
            - ${RABBIT_PORT_WEB}:15672
        environment:
            DEFAULT_NODE_PORT: ${RABBIT_PORT}
            RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBIT_PWD}
        volumes:
        - ./data/:/var/lib/rabbitmq/
        - ./log/:/var/log/rabbitmq/

