services:
  minio:
    image: minio/minio:latest
    container_name: ${MINIO}
    restart: unless-stopped
    ports:
      - "${HOST}:${MINIO_PORT_API}:9000" # API S3
      - "${HOST}:${MINIO_PORT_WEB}:9001" # Web‑консоль
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":${MINIO_PORT_WEB}"

volumes:
  minio-data: