services:

  minio:
    image: minio/minio:latest
    container_name: ${MINIO}
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER:            ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD:        ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL:           ${MINIO_SERVER_URL}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    volumes:
      - minio-data_sal:/data
    command: server /data --console-address ":9001"

  minio-nginx:
    image: nginx
    container_name: ${MINIO}-nginx
    restart: unless-stopped
    ports:
      - "${MINIO_SERVER_PORT}:${MINIO_SERVER_PORT}"
    env_file:
      - .env
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/templates:/etc/nginx/templates
      - ${MINIO_SSL}:/etc/nginx/ssl:ro
      - ${MINIO_LOG}/${MINIO}:/var/log/nginx
    depends_on:
      - minio

volumes:
  minio-data_sal: