services:

  minio:
    image: minio/minio:latest
    container_name: ${MINIO}
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":${MINIO_PORT_WEB}"

  minio-nginx:
    image: nginx
    container_name: ${MINIO_NGINX}
    restart: unless-stopped
    ports:
      - "${MINIO_PORT_API}:${MINIO_PORT_API}"
      - "${MINIO_PORT_WEB}:${MINIO_PORT_WEB}"
    env_file:
        - .env
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/templates:/etc/nginx/templates
      - /home/prod/.self_ssl:/etc/nginx/ssl:ro
      - /home/prod/LOGS/${MINIO}:/var/log/nginx
    depends_on:
      - minio

volumes:
  minio-data: